spring.application.name=cloudshield-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/cloudshield
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false